### ISSUE TITLE
Database Migration Issue

### ISSUE THREAD

**Issue by chirag-nandaniya** [stepanenko3/nova-health#2]
I have install package with Nova 4.32 today. Its give table missing error while with "php artisan migrate", its give nothing to migrate.

Refer screenshot for more details.

![Screenshot from 2024-02-01 19-41-54](https://github.com/stepanenko3/nova-health/assets/6713158/bffce5d1-146e-40d9-a90d-b95e8ef643cc)

**Comment by stepanenko3** [comment]
Hi, @chirag-nandaniya
Watch the package: https://github.com/spatie/laravel-health
